// Code generated by gvk-dirs-generator DO NOT EDIT.
package autoscalingv1gvk

import (
	"k8s.io/api/autoscaling/v1"
	"reflect"
)

var HorizontalPodAutoscaler = v1.SchemeGroupVersion.WithKind(reflect.TypeOf(&v1.HorizontalPodAutoscaler{}).Name())
var HorizontalPodAutoscalerList = v1.SchemeGroupVersion.WithKind(reflect.TypeOf(&v1.HorizontalPodAutoscalerList{}).Name())
var Scale = v1.SchemeGroupVersion.WithKind(reflect.TypeOf(&v1.Scale{}).Name())
