// Code generated by gvk-dirs-generator DO NOT EDIT.
package autoscalingv2beta2gvk

import (
	"k8s.io/api/autoscaling/v2beta2"
	"reflect"
)

var HorizontalPodAutoscaler = v2beta2.SchemeGroupVersion.WithKind(reflect.TypeOf(&v2beta2.HorizontalPodAutoscaler{}).Name())
var HorizontalPodAutoscalerList = v2beta2.SchemeGroupVersion.WithKind(reflect.TypeOf(&v2beta2.HorizontalPodAutoscalerList{}).Name())
