// Code generated by gvk-dirs-generator DO NOT EDIT.
package autoscalingv2beta1gvk

import (
	"k8s.io/api/autoscaling/v2beta1"
	"reflect"
)

var HorizontalPodAutoscaler = v2beta1.SchemeGroupVersion.WithKind(reflect.TypeOf(&v2beta1.HorizontalPodAutoscaler{}).Name())
var HorizontalPodAutoscalerList = v2beta1.SchemeGroupVersion.WithKind(reflect.TypeOf(&v2beta1.HorizontalPodAutoscalerList{}).Name())
