version: 2
updates:
  - package-ecosystem: "gomod"
    schedule:
      interval: weekly
    directory: "/"
    groups:
      k8s-deps:
        patterns:
          - "k8s.io/*"
      otel-dependencies:
        patterns:
          - "go.opentelemetry.io/*"
      golang-org-x:
        patterns:
          - "golang.org/x/*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
