version: "2"
linters:
  default: none
  enable:
    - asciicheck
    - depguard
    - durationcheck
    - errcheck
    - forcetypeassert
    - goconst
    - gocritic
    - gosec
    - govet
    - makezero
    - nosprintfhostport
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
  settings:
    depguard:
      rules:
        no-exp-slog:
          deny:
            - pkg: golang.org/x/exp/slog
              desc: please use "log/slog" instead
        no-old-yaml-pkg:
          deny:
            - pkg: gopkg.in/yaml.v2
              desc: please use gopkg.in/yaml.v3, not v2
        no-sync-atomic:
          deny:
            - pkg: sync/atomic
              desc: please use type-safe atomics from go.uber.org/atomic
        only-std-errors-pkg:
          deny:
            - pkg: github.com/pkg/errors
              desc: Should be replaced by standard lib "errors" package or "fmt.Errorf" or "go.uber.org/multierr" package
            - pkg: github.com/go-errors/errors
              desc: Should be replaced by standard lib "errors" package or "fmt.Errorf" or "go.uber.org/multierr" package
            - pkg: golang.org/x/xerrors
              desc: Should be replaced by standard lib "errors" package or "fmt.Errorf" or "go.uber.org/multierr" package
    errcheck:
      check-type-assertions: true
      check-blank: true
    gocritic:
      disabled-checks:
        - rangeValCopy
        - unnamedResult
        - hugeParam
        - paramTypeCombine
        - typeDefFirst
        - whyNoLint
      enabled-tags:
        - performance
        - diagnostic
        - opinionated
        - style
        - experimental
    revive:
      rules:
        - name: indent-error-flow
          disabled: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - revive
        text: blank-imports
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(aerf.io/k8sutils)
        - blank
        - dot
      custom-order: true
    gofmt:
      simplify: true
      rewrite-rules:
        - pattern: interface{}
          replacement: any
        - pattern: a[b:len(a)]
          replacement: a[b:]
    gofumpt:
      extra-rules: true
