// Code generated by gvk-dirs-generator DO NOT EDIT.
package appsv1gvk

import (
	"reflect"
	"k8s.io/api/apps/v1"
)
var ControllerRevision = v1.SchemeGroupVersion.WithKind(reflect.TypeOf(&v1.ControllerRevision{}).Name())
var ControllerRevisionList = v1.SchemeGroupVersion.WithKind(reflect.TypeOf(&v1.ControllerRevisionList{}).Name())
var DaemonSet = v1.SchemeGroupVersion.WithKind(reflect.TypeOf(&v1.DaemonSet{}).Name())
var DaemonSetList = v1.SchemeGroupVersion.WithKind(reflect.TypeOf(&v1.DaemonSetList{}).Name())
var Deployment = v1.SchemeGroupVersion.WithKind(reflect.TypeOf(&v1.Deployment{}).Name())
var DeploymentList = v1.SchemeGroupVersion.WithKind(reflect.TypeOf(&v1.DeploymentList{}).Name())
var ReplicaSet = v1.SchemeGroupVersion.WithKind(reflect.TypeOf(&v1.ReplicaSet{}).Name())
var ReplicaSetList = v1.SchemeGroupVersion.WithKind(reflect.TypeOf(&v1.ReplicaSetList{}).Name())
var StatefulSet = v1.SchemeGroupVersion.WithKind(reflect.TypeOf(&v1.StatefulSet{}).Name())
var StatefulSetList = v1.SchemeGroupVersion.WithKind(reflect.TypeOf(&v1.StatefulSetList{}).Name())
