// Code generated by gvk-dirs-generator DO NOT EDIT.
package appsv1beta2gvk

import (
	"k8s.io/api/apps/v1beta2"
	"reflect"
)

var ControllerRevision = v1beta2.SchemeGroupVersion.WithKind(reflect.TypeOf(&v1beta2.ControllerRevision{}).Name())
var ControllerRevisionList = v1beta2.SchemeGroupVersion.WithKind(reflect.TypeOf(&v1beta2.ControllerRevisionList{}).Name())
var DaemonSet = v1beta2.SchemeGroupVersion.WithKind(reflect.TypeOf(&v1beta2.DaemonSet{}).Name())
var DaemonSetList = v1beta2.SchemeGroupVersion.WithKind(reflect.TypeOf(&v1beta2.DaemonSetList{}).Name())
var Deployment = v1beta2.SchemeGroupVersion.WithKind(reflect.TypeOf(&v1beta2.Deployment{}).Name())
var DeploymentList = v1beta2.SchemeGroupVersion.WithKind(reflect.TypeOf(&v1beta2.DeploymentList{}).Name())
var ReplicaSet = v1beta2.SchemeGroupVersion.WithKind(reflect.TypeOf(&v1beta2.ReplicaSet{}).Name())
var ReplicaSetList = v1beta2.SchemeGroupVersion.WithKind(reflect.TypeOf(&v1beta2.ReplicaSetList{}).Name())
var Scale = v1beta2.SchemeGroupVersion.WithKind(reflect.TypeOf(&v1beta2.Scale{}).Name())
var StatefulSet = v1beta2.SchemeGroupVersion.WithKind(reflect.TypeOf(&v1beta2.StatefulSet{}).Name())
var StatefulSetList = v1beta2.SchemeGroupVersion.WithKind(reflect.TypeOf(&v1beta2.StatefulSetList{}).Name())
