// Code generated by gvk-dirs-generator DO NOT EDIT.
package storagev1gvk

import (
	"reflect"
	"k8s.io/api/storage/v1"
)
var CSIDriver = v1.SchemeGroupVersion.WithKind(reflect.TypeOf(&v1.CSIDriver{}).Name())
var CSIDriverList = v1.SchemeGroupVersion.WithKind(reflect.TypeOf(&v1.CSIDriverList{}).Name())
var CSINode = v1.SchemeGroupVersion.WithKind(reflect.TypeOf(&v1.CSINode{}).Name())
var CSINodeList = v1.SchemeGroupVersion.WithKind(reflect.TypeOf(&v1.CSINodeList{}).Name())
var CSIStorageCapacity = v1.SchemeGroupVersion.WithKind(reflect.TypeOf(&v1.CSIStorageCapacity{}).Name())
var CSIStorageCapacityList = v1.SchemeGroupVersion.WithKind(reflect.TypeOf(&v1.CSIStorageCapacityList{}).Name())
var StorageClass = v1.SchemeGroupVersion.WithKind(reflect.TypeOf(&v1.StorageClass{}).Name())
var StorageClassList = v1.SchemeGroupVersion.WithKind(reflect.TypeOf(&v1.StorageClassList{}).Name())
var VolumeAttachment = v1.SchemeGroupVersion.WithKind(reflect.TypeOf(&v1.VolumeAttachment{}).Name())
var VolumeAttachmentList = v1.SchemeGroupVersion.WithKind(reflect.TypeOf(&v1.VolumeAttachmentList{}).Name())
