// Code generated by gvk-dirs-generator DO NOT EDIT.
package coordinationv1beta1gvk

import (
	"reflect"
	"k8s.io/api/coordination/v1beta1"
)
var Lease = v1beta1.SchemeGroupVersion.WithKind(reflect.TypeOf(&v1beta1.Lease{}).Name())
var LeaseList = v1beta1.SchemeGroupVersion.WithKind(reflect.TypeOf(&v1beta1.LeaseList{}).Name())
var LeaseCandidate = v1beta1.SchemeGroupVersion.WithKind(reflect.TypeOf(&v1beta1.LeaseCandidate{}).Name())
var LeaseCandidateList = v1beta1.SchemeGroupVersion.WithKind(reflect.TypeOf(&v1beta1.LeaseCandidateList{}).Name())
