// Code generated by gvk-dirs-generator DO NOT EDIT.
package coordinationv1beta1gvk

import (
	"k8s.io/api/coordination/v1beta1"
	"reflect"
)

var Lease = v1beta1.SchemeGroupVersion.WithKind(reflect.TypeOf(&v1beta1.Lease{}).Name())
var LeaseList = v1beta1.SchemeGroupVersion.WithKind(reflect.TypeOf(&v1beta1.LeaseList{}).Name())
