// Code generated by gvk-dirs-generator DO NOT EDIT.
package networkingv1gvk

import (
	"k8s.io/api/networking/v1"
	"reflect"
)

var Ingress = v1.SchemeGroupVersion.WithKind(reflect.TypeOf(&v1.Ingress{}).Name())
var IngressList = v1.SchemeGroupVersion.WithKind(reflect.TypeOf(&v1.IngressList{}).Name())
var IngressClass = v1.SchemeGroupVersion.WithKind(reflect.TypeOf(&v1.IngressClass{}).Name())
var IngressClassList = v1.SchemeGroupVersion.WithKind(reflect.TypeOf(&v1.IngressClassList{}).Name())
var NetworkPolicy = v1.SchemeGroupVersion.WithKind(reflect.TypeOf(&v1.NetworkPolicy{}).Name())
var NetworkPolicyList = v1.SchemeGroupVersion.WithKind(reflect.TypeOf(&v1.NetworkPolicyList{}).Name())
