// Code generated by gvk-dirs-generator DO NOT EDIT.
package discoveryv1gvk

import (
	"k8s.io/api/discovery/v1"
	"reflect"
)

var EndpointSlice = v1.SchemeGroupVersion.WithKind(reflect.TypeOf(&v1.EndpointSlice{}).Name())
var EndpointSliceList = v1.SchemeGroupVersion.WithKind(reflect.TypeOf(&v1.EndpointSliceList{}).Name())
