// Code generated by gvk-dirs-generator DO NOT EDIT.
package batchv1gvk

import (
	"reflect"
	"k8s.io/api/batch/v1"
)
var CronJob = v1.SchemeGroupVersion.WithKind(reflect.TypeOf(&v1.CronJob{}).Name())
var CronJobList = v1.SchemeGroupVersion.WithKind(reflect.TypeOf(&v1.CronJobList{}).Name())
var Job = v1.SchemeGroupVersion.WithKind(reflect.TypeOf(&v1.Job{}).Name())
var JobList = v1.SchemeGroupVersion.WithKind(reflect.TypeOf(&v1.JobList{}).Name())
