// Code generated by gvk-dirs-generator DO NOT EDIT.
package schedulingv1gvk

import (
	"k8s.io/api/scheduling/v1"
	"reflect"
)

var PriorityClass = v1.SchemeGroupVersion.WithKind(reflect.TypeOf(&v1.PriorityClass{}).Name())
var PriorityClassList = v1.SchemeGroupVersion.WithKind(reflect.TypeOf(&v1.PriorityClassList{}).Name())
