// Code generated by gvk-dirs-generator DO NOT EDIT.
package appsv1beta1gvk

import (
	"k8s.io/api/apps/v1beta1"
	"reflect"
)

var ControllerRevision = v1beta1.SchemeGroupVersion.WithKind(reflect.TypeOf(&v1beta1.ControllerRevision{}).Name())
var ControllerRevisionList = v1beta1.SchemeGroupVersion.WithKind(reflect.TypeOf(&v1beta1.ControllerRevisionList{}).Name())
var Deployment = v1beta1.SchemeGroupVersion.WithKind(reflect.TypeOf(&v1beta1.Deployment{}).Name())
var DeploymentList = v1beta1.SchemeGroupVersion.WithKind(reflect.TypeOf(&v1beta1.DeploymentList{}).Name())
var Scale = v1beta1.SchemeGroupVersion.WithKind(reflect.TypeOf(&v1beta1.Scale{}).Name())
var StatefulSet = v1beta1.SchemeGroupVersion.WithKind(reflect.TypeOf(&v1beta1.StatefulSet{}).Name())
var StatefulSetList = v1beta1.SchemeGroupVersion.WithKind(reflect.TypeOf(&v1beta1.StatefulSetList{}).Name())
