// Code generated by gvk-dirs-generator DO NOT EDIT.
package rbacv1gvk

import (
	"k8s.io/api/rbac/v1"
	"reflect"
)

var ClusterRole = v1.SchemeGroupVersion.WithKind(reflect.TypeOf(&v1.ClusterRole{}).Name())
var ClusterRoleList = v1.SchemeGroupVersion.WithKind(reflect.TypeOf(&v1.ClusterRoleList{}).Name())
var ClusterRoleBinding = v1.SchemeGroupVersion.WithKind(reflect.TypeOf(&v1.ClusterRoleBinding{}).Name())
var ClusterRoleBindingList = v1.SchemeGroupVersion.WithKind(reflect.TypeOf(&v1.ClusterRoleBindingList{}).Name())
var Role = v1.SchemeGroupVersion.WithKind(reflect.TypeOf(&v1.Role{}).Name())
var RoleList = v1.SchemeGroupVersion.WithKind(reflect.TypeOf(&v1.RoleList{}).Name())
var RoleBinding = v1.SchemeGroupVersion.WithKind(reflect.TypeOf(&v1.RoleBinding{}).Name())
var RoleBindingList = v1.SchemeGroupVersion.WithKind(reflect.TypeOf(&v1.RoleBindingList{}).Name())
