// Code generated by gvk-dirs-generator DO NOT EDIT.
package policyv1gvk

import (
	"k8s.io/api/policy/v1"
	"reflect"
)

var PodDisruptionBudget = v1.SchemeGroupVersion.WithKind(reflect.TypeOf(&v1.PodDisruptionBudget{}).Name())
var PodDisruptionBudgetList = v1.SchemeGroupVersion.WithKind(reflect.TypeOf(&v1.PodDisruptionBudgetList{}).Name())
